"""Add memory tables

Revision ID: 83abeafb8378
Revises: 8566e8eb7133
Create Date: 2026-07-13 15:47:26.804497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83abeafb8378'
down_revision: Union[str, Sequence[str], None] = '8566e8eb7133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_memory_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('raw_fact', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejected_memory_log_memory_type'), 'rejected_memory_log', ['memory_type'], unique=False)
    op.create_index(op.f('ix_rejected_memory_log_uid'), 'rejected_memory_log', ['uid'], unique=False)
    
    op.create_table('user_episodic_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_episodic_memory_is_archived'), 'user_episodic_memory', ['is_archived'], unique=False)
    op.create_index(op.f('ix_user_episodic_memory_thread_id'), 'user_episodic_memory', ['thread_id'], unique=False)
    op.create_index(op.f('ix_user_episodic_memory_uid'), 'user_episodic_memory', ['uid'], unique=False)
    
    op.create_table('user_procedural_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_procedural_memory_is_active'), 'user_procedural_memory', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_procedural_memory_uid'), 'user_procedural_memory', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_procedural_memory_uid'), table_name='user_procedural_memory')
    op.drop_index(op.f('ix_user_procedural_memory_is_active'), table_name='user_procedural_memory')
    op.drop_table('user_procedural_memory')
    op.drop_index(op.f('ix_user_episodic_memory_uid'), table_name='user_episodic_memory')
    op.drop_index(op.f('ix_user_episodic_memory_thread_id'), table_name='user_episodic_memory')
    op.drop_index(op.f('ix_user_episodic_memory_is_archived'), table_name='user_episodic_memory')
    op.drop_table('user_episodic_memory')
    op.drop_index(op.f('ix_rejected_memory_log_uid'), table_name='rejected_memory_log')
    op.drop_index(op.f('ix_rejected_memory_log_memory_type'), table_name='rejected_memory_log')
    op.drop_table('rejected_memory_log')
    # ### end Alembic commands ###
