"""Add AuditLog with Hash Chain

Revision ID: 96d0b2c39695
Revises: 83abeafb8378
Create Date: 2026-07-14 14:09:58.246431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d0b2c39695'
down_revision: Union[str, Sequence[str], None] = '83abeafb8378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_migrations')
    op.alter_column('agent_runs', 'conversation_thread_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               comment='Conversation thread ID snapshot')
    op.alter_column('agent_runs', 'agent_slug',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               comment='Agent slug')
    op.alter_column('agent_runs', 'created_by_run_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Run that created this run',
               existing_nullable=True)
    op.alter_column('agent_runs', 'subagent_thread_relation_id',
               existing_type=sa.INTEGER(),
               comment='Subagent thread relation record ID',
               existing_nullable=True)
    op.drop_index(op.f('idx_agent_runs_conversation_thread_created'), table_name='agent_runs')
    op.drop_index(op.f('idx_agent_runs_created_by_run_created'), table_name='agent_runs')
    op.drop_index(op.f('idx_agent_runs_status_updated'), table_name='agent_runs')
    op.drop_index(op.f('idx_agent_runs_subagent_lookup'), table_name='agent_runs')
    op.drop_index(op.f('idx_agent_runs_uid_created'), table_name='agent_runs')
    op.create_index(op.f('ix_agent_runs_agent_slug'), 'agent_runs', ['agent_slug'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_thread_id'), 'agent_runs', ['conversation_thread_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_by_run_id'), 'agent_runs', ['created_by_run_id'], unique=False)
    op.create_foreign_key(None, 'agent_runs', 'subagent_threads', ['subagent_thread_relation_id'], ['id'])
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Agent slug (legacy column name: agent_id)',
               existing_comment='Agent ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_evaluation_runs_started'), table_name='evaluation_runs')
    op.drop_index(op.f('idx_kb_name'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_kb_type'), table_name='knowledge_bases')
    op.alter_column('knowledge_chunks', 'neo4j_sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Neo4j sync status: pending/synced/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_kf_hash'), table_name='knowledge_files')
    op.drop_index(op.f('idx_kf_kb_filename'), table_name='knowledge_files')
    op.drop_index(op.f('idx_kf_kb_id'), table_name='knowledge_files')
    op.drop_index(op.f('idx_kf_parent'), table_name='knowledge_files')
    op.drop_index(op.f('idx_kf_status'), table_name='knowledge_files')
    op.drop_index(op.f('ix_subagent_threads_parent_conversation'), table_name='subagent_threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subagent_threads_parent_conversation'), 'subagent_threads', ['parent_conversation_id'], unique=False)
    op.create_index(op.f('idx_kf_status'), 'knowledge_files', ['status'], unique=False)
    op.create_index(op.f('idx_kf_parent'), 'knowledge_files', ['parent_id'], unique=False)
    op.create_index(op.f('idx_kf_kb_id'), 'knowledge_files', ['kb_id'], unique=False)
    op.create_index(op.f('idx_kf_kb_filename'), 'knowledge_files', ['kb_id', 'filename'], unique=False)
    op.create_index(op.f('idx_kf_hash'), 'knowledge_files', ['content_hash'], unique=False)
    op.alter_column('knowledge_chunks', 'neo4j_sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Neo4j sync status: pending/synced/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('idx_kb_type'), 'knowledge_bases', ['kb_type'], unique=False)
    op.create_index(op.f('idx_kb_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_started'), 'evaluation_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Agent ID',
               existing_comment='Agent slug (legacy column name: agent_id)',
               existing_nullable=False)
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runs_created_by_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_thread_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_slug'), table_name='agent_runs')
    op.create_index(op.f('idx_agent_runs_uid_created'), 'agent_runs', ['uid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_runs_subagent_lookup'), 'agent_runs', ['uid', 'conversation_thread_id', 'run_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_runs_status_updated'), 'agent_runs', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('idx_agent_runs_created_by_run_created'), 'agent_runs', ['created_by_run_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_runs_conversation_thread_created'), 'agent_runs', ['conversation_thread_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('agent_runs', 'subagent_thread_relation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Subagent thread relation record ID',
               existing_nullable=True)
    op.alter_column('agent_runs', 'created_by_run_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Run that created this run',
               existing_nullable=True)
    op.alter_column('agent_runs', 'agent_slug',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               comment=None,
               existing_comment='Agent slug')
    op.alter_column('agent_runs', 'conversation_thread_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               comment=None,
               existing_comment='Conversation thread ID snapshot')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    # ### end Alembic commands ###
