"""refactor_indexing_architecture

Revision ID: b2c263690c44
Revises: 39fc6f7b8af0
Create Date: 2026-08-11 14:50:21.916830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c263690c44'
down_revision: Union[str, Sequence[str], None] = '39fc6f7b8af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=True),
    sa.Column('embedding_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_embedding_cache_key')
    )
    op.create_index(op.f('ix_embedding_cache_cache_key'), 'embedding_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_embedding_cache_file_id'), 'embedding_cache', ['file_id'], unique=False)
    op.create_table('index_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('chunking_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=256), nullable=False),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_id', name='uq_index_manifests_manifest_id')
    )
    op.create_index(op.f('ix_index_manifests_file_id'), 'index_manifests', ['file_id'], unique=False)
    op.create_index(op.f('ix_index_manifests_manifest_id'), 'index_manifests', ['manifest_id'], unique=True)
    op.create_index(op.f('ix_index_manifests_status'), 'index_manifests', ['status'], unique=False)
    op.add_column('knowledge_files', sa.Column('chunking_version', sa.String(length=64), nullable=True))
    op.add_column('knowledge_files', sa.Column('embedding_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_files', 'embedding_version')
    op.drop_column('knowledge_files', 'chunking_version')
    op.drop_index(op.f('ix_index_manifests_status'), table_name='index_manifests')
    op.drop_index(op.f('ix_index_manifests_manifest_id'), table_name='index_manifests')
    op.drop_index(op.f('ix_index_manifests_file_id'), table_name='index_manifests')
    op.drop_table('index_manifests')
    op.drop_index(op.f('ix_embedding_cache_file_id'), table_name='embedding_cache')
    op.drop_index(op.f('ix_embedding_cache_cache_key'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
